#!/bin/bash
PACKMAN_GROUP=packman
PACKMAN_USER=packman
PACKMAN_PREFIX=/home/packman

if ! getent group $PACKMAN_GROUP >/dev/null; then
        addgroup --system --force-badname --quiet $PACKMAN_GROUP  
fi

if ! getent passwd $PACKMAN_USER >/dev/null; then
        adduser --system --force-badname --quiet \
            --home $PACKMAN_PREFIX --no-create-home \
            --shell /bin/bash \
    --uid 7373 \
            --group $PACKMAN_GROUP
        usermod -c "packman user" $PACKMAN_USER
fi

